using System;
using System.Reflection;
using System.Runtime.InteropServices;
using log4net.Config;

//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(false)]
[assembly: AssemblyVersionAttribute("0.36.4818.8638")]
[assembly: AssemblyTitleAttribute("Concurrent Versions System (sharpCVS) (client)")]
[assembly: AssemblyDescriptionAttribute("win32; net-1.1; 2005/01/18 11:59:39")]
[assembly: AssemblyCopyrightAttribute("Mike Krueger 2001-2002, SharpCvsLib Developers 2003-2005\r\n\r\nCVS may be copied onl" +
"y under the terms of the GNU General Public License,\r\na copy of which can be fou" +
"nd with the CVS distribution kit.")]
[assembly: AssemblyCompanyAttribute("SharpCvsLib - http://sharpcvslib.sourceforge.net")]
[assembly: log4net.Config.XmlConfigurator(Watch=true)]

