using System;
using System.Reflection;
using System.EnterpriseServices;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(true)]
[assembly: AssemblyVersionAttribute("0.34.3614.413")]
[assembly: AssemblyTitleAttribute("SharpCvsLib")]
[assembly: AssemblyDescriptionAttribute("Cvs client library written in c#")]
[assembly: AssemblyCopyrightAttribute("Mike Krueger 2001-2002, SharpCvsLib Developers 2003")]
[assembly: ApplicationNameAttribute("SharpCvsLib")]

