using System;
using System.Reflection;
using System.EnterpriseServices;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(true)]
[assembly: AssemblyVersionAttribute("0.35.3721.417")]
[assembly: AssemblyTitleAttribute("Concurrent Versions System (sharpCVS) (client)")]
[assembly: AssemblyDescriptionAttribute("win32; net-1.0; 2004/02/21 01:09:39")]
[assembly: AssemblyCopyrightAttribute("Mike Krueger 2001-2002, SharpCvsLib Developers 2003-2004\r\n\r\nCVS may be copied onl" +
"y under the terms of the GNU General Public License,\r\na copy of which can be fou" +
"nd with the CVS distribution kit.")]
[assembly: AssemblyCompanyAttribute("SharpCvsLib - http://sharpcvslib.sourceforge.net")]
[assembly: ApplicationNameAttribute("SharpCvsLib")]

